--- 
- name: deploy 
  hosts: appserver 
  become: yes 
  tasks: 
    - name: update ubuntu packages and install java
      apt:
        name: openjdk-11-jdk 
        update_cache: yes
        state: present 
    - name: creating a springpetclinic directory 
      file:
        path: /usr/share/springpetclinic 
        state: directory
   
    - name: downloading the file from s3 
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar

    - name: creating a user 
      user: 
        name: springbootuser
        password: springbootuser
        state: present 

    - name: changing ownership of a file 
      file: 
        path:  /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500' 
        state: file

    - name: copying the service file to ans nodes
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service 

    - name: enabiling and starting the service
      systemd: 
        name: springpetclinic.service
        enabled: yes
        state: started 
        masked: no 
         








    

