--- 
- name: deploy 
  hosts: appserver 
  become: yes 
  vars:
    java_package: openjdk-11-jdk 
    app_dir: /usr/share/springpetclinic
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: spring-petclinic-2.4.2.jar
    app_username: springbootuser

  tasks: 
    - name: update ubuntu packages and install java
      apt:
        name: "{{java_package}}"
        update_cache: yes
        state: present 
    - name: creating a springpetclinic directory 
      file:
        path: "{{app_dir}}"
        state: directory
   
    - name: downloading the file from s3 
      get_url:
        url: "{{app_download_url}}"
        dest: "{{app_dir}}/{{app_file_name}}"

    - name: creating a user 
      user: 
        name: "{{app_username}}"
        password: "{{app_username}}"
        state: present 

    - name: changing ownership of a file 
      file: 
        path:  /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500' 
        state: file

    - name: copying the service file to ans nodes
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Enable and start spring petclinic
      systemd:
        daemon_reload: yes 
        name: springpetclinic.service
        enabled: yes
        state: started
        masked: no 
         








    

